### ISSUE TITLE
반응형 이슈 리스트

### ISSUE THREAD

**Issue by zoomKoding** [woowa-techcamp-2020/bmart-6#105]
## 반응형 이슈 리스트
- [x] Sort DropDown Icon
- [x] Sort Modal 크기
- [x] 대표 상품 헤더 스크롤 포인트
- [x] 메뉴 페이지 텍스트
- [x] 주문 생성 페이지 체크박스
- [x] 주문 생성 페이지 선택 비우기 2줄 됨
- [x] 로그인 페이지 ('로그인이 필요' 텍스트)
- [x] 회원가입 페이지 validator 메시지

**Comment by wudys** [comment]
메인 메뉴 카테고리 아이콘 (이미지) 사이즈!

**Comment by wudys** [comment]
addCartModal
