### ISSUE TITLE
ERD 작성하기

### ISSUE THREAD

**Issue by zoomKoding** [woowa-techcamp-2020/bmart-6#2]
## ERD v1.0.0
![bmart6-erd](https://user-images.githubusercontent.com/36878344/89800342-9f5de000-db69-11ea-8681-2718fdb8df98.png)

**Comment by doonguk** [comment]
![image](https://user-images.githubusercontent.com/39187116/90311767-b457bc00-df39-11ea-9db4-09af8f9f7e81.png)

**Comment by doonguk** [comment]
ERD 최종본!
